FROM node:20-alpine
WORKDIR /app
COPY package*.json .
RUN npm install
COPY vite.config.ts index.html tsconfig.json tsconfig.node.json ./
COPY src ./src
ENV NODE_ENV=development
ENV CHOKIDAR_USEPOLLING=true
EXPOSE 5173
CMD ["npm", "run", "dev"]
